# Generated by Django 5.0.6 on 2024-07-11 11:26

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=100))),
                ('product_image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(max_length=400)),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel')),
            ],
        ),
    ]
