# Generated by Django 5.0.6 on 2024-07-17 09:48

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='product_image',
            field=models.ImageField(upload_to='productsImages/'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='product_name'),
        ),
    ]
